---
layout: post
title: JS异步编程
tags:
- ES6
- Promise
- Generator
- async
date: 2017-04-20 11:00:00.000000000 +09:00
---

## 异步编程发展
+ 回调事件
+ 事件监听
+ 发布／订阅
+ Promise对象
+ Generator函数
+ async函数

## Promise

### 含义
所谓``Promise``，简单说就是一个容器，里面保存着某个未来才会结束的事件（通常是一个异步操作）的结果
从语法上说，Promise 是一个对象，从它可以获取异步操作的消息

+ 对象的状态不受外界影响。Promise对象代表一个异步操作，有三种状态：Pending（进行中）、Resolved（已完成，又称 Fulfilled）和Rejected（已失败）
只有异步操作的结果，可以决定当前是哪一种状态，任何其他操作都无法改变这个状态
+ 一旦状态改变，就不会再变，任何时候都可以得到这个结果。Promise对象的状态改变，只有两种可能：从``Pending``变为``Resolved``和从``Pending``变为``Rejected``

Promise也有一些缺点。首先，无法取消Promise，一旦新建它就会立即执行，无法中途取消
其次，如果不设置回调函数，Promise内部抛出的错误，不会反应到外部
第三，当处于Pending状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）

### 基本用法
```javascript
var promise = new Promise(function(resolve, reject) {
  // ... some code

  if (/* 异步操作成功 */){
    resolve(value);
  } else {
    reject(error);
  }
});
```
Promise构造函数接受一个函数作为参数，该函数的两个参数分别是``resolve``和``reject``
+ ``resolve``函数的作用是，将Promise对象的状态从“未完成”变为“成功”
+ ``reject``函数的作用是，将Promise对象的状态从“未完成”变为“失败”

Promise实例生成以后，可以用then方法分别指定Resolved状态和Reject状态的回调函数
```javascript
promise.then(function(value) {
  // success
}, function(error) {
  // failure
});
```
**Promise新建后就会立即执行**
异步加载图片的例子:
```javascript
function loadImageAsync(url) {
  return new Promise(function(resolve, reject) {
    var image = new Image();

    image.onload = function() {
      resolve(image);
    };

    image.onerror = function() {
      reject(new Error('Could not load image at ' + url));
    };

    image.src = url;
  });
}
```
如果调用resolve函数和reject函数时带有参数，那么它们的参数会被传递给回调函数

### Promise.prototype.then()
``then``方法的第一个参数是Resolved状态的回调函数，第二个参数（可选）是Rejected状态的回调函数
then方法返回的是一个新的Promise实例（注意，不是原来那个Promise实例）。因此可以采用链式写法，即then方法后面再调用另一个then方法
```javascript
getjavascriptON("/posts.javascripton").then(function(javascripton) {
  return javascripton.post;
}).then(function(post) {
  // ...
});
```
第一个回调函数完成以后，会将返回结果作为参数，传入第二个回调函数

采用链式的then，可以指定一组按照次序调用的回调函数
这时，前一个回调函数，有可能返回的还是一个Promise对象（即有异步操作），这时后一个回调函数，就会等待该Promise对象的状态发生变化，才会被调用

### Promise.prototype.catch()
``Promise.prototype.catch``方法是``.then(null, rejection)``的别名

Promise 对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止。也就是说，错误总是会被下一个``catch``语句捕获

一般来说，不要在then方法里面定义Reject状态的回调函数（即then的第二个参数），总是使用catch方法

``catch``方法返回的还是一个 Promise 对象，因此后面还可以接着调用``then``方法

### Promise.all()
``Promise.all``方法用于将多个Promise实例，包装成一个新的Promise实例
```javascript
var p = Promise.all([p1, p2, p3]);
```
p的状态由p1、p2、p3决定，分成两种情况
1. 只有p1、p2、p3的状态都变成fulfilled，p的状态才会变成fulfilled，此时p1、p2、p3的返回值组成一个数组，传递给p的回调函数
2. 只要p1、p2、p3之中有一个被rejected，p的状态就变成rejected，此时第一个被reject的实例的返回值，会传递给p的回调函数

### Promise.race()
```javascript
var p = Promise.race([p1, p2, p3]);
```

### Promise.resolve()
有时需要将现有对象转为Promise对象，Promise.resolve方法就起到这个作用
```javascript
var javascriptPromise = Promise.resolve($.ajax('/whatever.javascripton'));
```
Promise.resolve方法的参数分成四种情况:
+ **参数是一个Promise实例**: 将不做任何修改、原封不动地返回这个实例
+ **参数是一个``thenable``对象**: Promise.resolve方法会将这个对象转为Promise对象，然后就立即执行thenable对象的then方法
+ **参数不是具有then方法的对象，或根本就不是对象**: 返回一个新的Promise对象，状态为Resolved
+ **不带有任何参数**: 直接返回一个``resolved``状态的Promise对象

需要注意的是，立即resolve的Promise对象，是在本轮“事件循环”（event loop）的结束时，而不是在下一轮“事件循环”的开始时
```javascript
setTimeout(function () {
  console.log('three');
}, 0);

Promise.resolve().then(function () {
  console.log('two');
});

console.log('one');

// one
// two
// three
```
``setTimeout(fn, 0)``在下一轮“事件循环”开始时执行
``Promise.resolve()``在本轮“事件循环”结束时执行
``console.log('one')`则是立即执行，因此最先输出

### Promise.reject()
返回一个新的 Promise 实例，该实例的状态为``rejected``

Promise.reject()方法的参数，会**原封不动地作为``reject``的理由**

### 2个有用的附加方法
+ done(): 总是处于回调链的尾端，保证抛出任何可能出现的错误
+ finally(): 用于指定不管Promise对象最后状态如何，都会执行的操作

### Generator函数与Promise的结合(不太理解)
```javascript
function getFoo () {
  return new Promise(function (resolve, reject){
    resolve('foo');
  });
}

var g = function* () {
  try {
    var foo = yield getFoo();
    console.log(foo);
  } catch (e) {
    console.log(e);
  }
};

function run (generator) {
  var it = generator();

  function go(result) {
    if (result.done) return result.value;

    return result.value.then(function (value) {
      return go(it.next(value));
    }, function (error) {
      return go(it.throw(error));
    });
  }

  go(it.next());
}

run(g);
```

### Promise.try()
函数f是同步的，但是用 Promise 包装了以后，就变成异步执行了
没有一种方法，让同步函数同步执行，异步函数异步执行，并且让它们具有统一的 API ?
+ 写法1： async函数
```javascript
const f = () => console.log('now');
(async () => f())();
console.log('next');
// now
// next
```
+ 写法2：new Promise()
```javascript
const f = () => console.log('now');
(
  () => new Promise(
    resolve => resolve(f())
  )
)();
console.log('next');
// now
// next
```
+ 写法3：Promise.try()
```javascript
const f = () => console.log('now');
Promise.try(f);
console.log('next');

Promise.try(database.users.get({id: userId}))
  .then(...)
  .catch(...)
```
由于Promise.try为所有操作提供了统一的处理机制，所以如果想用then方法管理流程，最好都用Promise.try包装一下

## Generator函数

### 基本概念
```javascript
function* helloWorldGenerator() {
  yield 'hello';
  yield 'world';
  return 'ending';
}

var hw = helloWorldGenerator();

hw.next()
// { value: 'hello', done: false }

hw.next()
// { value: 'world', done: false }

hw.next()
// { value: 'ending', done: true }

hw.next()
// { value: undefined, done: true }
```
该函数有三个状态：hello，world和return语句（结束执行）

调用Generator函数后，该函数并不执行，返回的也不是函数运行结果，而是一个指向内部状态的指针对象

必须调用遍历器对象的next方法，使得指针移向下一个状态
也就是说，每次调用next方法，内部指针就从函数头部或上一次停下来的地方开始执行，直到遇到下一个yield语句（或return语句）为止

### yield语句
遍历器对象的next方法的运行逻辑如下:
1. 遇到yield语句，就暂停执行后面的操作，并将紧跟在yield后面的那个表达式的值，作为返回的对象的value属性值
2. 一次调用next方法时，再继续往下执行，直到遇到下一个yield语句
3. 如果没有再遇到新的yield语句，就一直运行到函数结束，直到return语句为止，并将return语句后面的表达式的值，作为返回的对象的value属性值
4. 如果该函数没有return语句，则返回的对象的value属性值为undefined

#### 与Iterator的关系
```javascript
var myIterable = {};
myIterable[Symbol.iterator] = function* () {
  yield 1;
  yield 2;
  yield 3;
};

[...myIterable] // [1, 2, 3]
```

#### next方法的参数
yield句本身没有返回值，或者说总是返回undefined
next方法可以带一个参数，该参数就会被当作上一个yield语句的返回值
```javascript
function* f() {
  for(var i = 0; true; i++) {
    var reset = yield i;
    if(reset) { i = -1; }
  }
}

var g = f();

g.next() // { value: 0, done: false }
g.next() // { value: 1, done: false }
g.next(true) // { value: 0, done: false }
```
由于next方法的参数表示上一个yield语句的返回值，所以第一次使用next方法时，不能带有参数

#### for...of循环
for...of循环可以自动遍历Generator函数时生成的Iterator对象，且此时不再需要调用next方法
```javascript
function* fibonacci() {
  let [prev, curr] = [0, 1];
  for (;;) {
    [prev, curr] = [curr, prev + curr];
    yield curr;
  }
}

for (let n of fibonacci()) {
  if (n > 1000) break;
  console.log(n);
}
```
面代码中，对象jane原生不具备``Iterator``接口，无法用``for...of``遍历
这时，我们通过Generator函数objectEntries为它加上遍历器接口，就可以用``for...of``遍历了
加上遍历器接口的另一种写法是，将``Generator``函数加到对象的``Symbol.iterator``属性上面

除了for...of循环以外，扩展运算符（...）、解构赋值和Array.from方法内部调用的，都是遍历器接口。这意味着，它们都可以将Generator函数返回的Iterator对象，作为参数

#### Generator.prototype.throw()
Generator函数返回的遍历器对象，都有一个throw方法，可以在函数体外抛出错误，然后在Generator函数体内捕获
```javascript
var g = function* () {
  try {
    yield;
  } catch (e) {
    console.log('内部捕获', e);
  }
};

var i = g();
i.next();

try {
  i.throw('a');
  i.throw('b');
} catch (e) {
  console.log('外部捕获', e);
}
// 内部捕获 a
// 外部捕获 b
```
throw方法被捕获以后，会附带执行下一条yield语句。也就是说，会附带执行一次next方法
```javascript
var gen = function* gen(){
  try {
    yield console.log('a');
  } catch (e) {
    // ...
  }
  yield console.log('b');
  yield console.log('c');
}

var g = gen();
g.next() // a
g.throw() // b
g.next() // c
```
只要Generator函数内部部署了try...catch代码块，那么遍历器的throw方法抛出的错误，不影响下一次遍历

这种函数体内捕获错误的机制，大大方便了对错误的处理
多个yield语句，可以只用一个try...catch代码块来捕获错误
如果使用回调函数的写法，想要捕获多个错误，就不得不为每个函数内部写一个错误处理语句，现在只在Generator函数内部写一次catch语句就可以了

一旦Generator执行过程中抛出错误，且没有被内部捕获，就不会再执行下去了
即JavaScript引擎认为这个Generator已经运行结束了

#### Generator.prototype.return()
返回给定的值，并且终结遍历Generator函数
```javascript
function* gen() {
  yield 1;
  yield 2;
  yield 3;
}

var g = gen();

g.next()        // { value: 1, done: false }
g.return('foo') // { value: "foo", done: true }
g.next()        // { value: undefined, done: true }
```
Generator函数内部有``try...finally``代码块，那么return方法会推迟到finally代码块执行完再执行
```javascript
function* numbers () {
  yield 1;
  try {
    yield 2;
    yield 3;
  } finally {
    yield 4;
    yield 5;
  }
  yield 6;
}
var g = numbers();
g.next() // { value: 1, done: false }
g.next() // { value: 2, done: false }
g.return(7) // { value: 4, done: false }
g.next() // { value: 5, done: false }
g.next() // { value: 7, done: true }
```

#### yield* 语句
如果在 Generator 函数内部，调用另一个 Generator 函数，默认情况下是没有效果的
yield* 用来在一个 Generator 函数里面执行另一个 Generator 函数
```javascript
function* bar() {
  yield 'x';
  yield* foo();
  yield 'y';
}

// 等同于
function* bar() {
  yield 'x';
  yield 'a';
  yield 'b';
  yield 'y';
}

// 等同于
function* bar() {
  yield 'x';
  for (let v of foo()) {
    yield v;
  }
  yield 'y';
}

for (let v of bar()){
  console.log(v);
}
// "x"
// "a"
// "b"
// "y"
```
实际上，任何数据结构只要有Iterator接口，就可以被yield*遍历
```javascript
let read = (function* () {
  yield 'hello';
  yield* 'hello';
})();

read.next().value // "hello"
// 字符串具有Iterator接口
read.next().value // "h"
```

#### 作为对象属性的Generator函数
```javascript
let obj = {
  * myGeneratorMethod() {
    ···
  }
};
```

#### Generator函数的this
Generator函数返回一个正常的对象实例，既可以用next方法，又可以获得正常的this
```javascript
function* gen() {
  this.a = 1;
  yield this.b = 2;
  yield this.c = 3;
}

function F() {
  return gen.call(gen.prototype);
}

var f = new F();

f.next();  // Object {value: 2, done: false}
f.next();  // Object {value: 3, done: false}
f.next();  // Object {value: undefined, done: true}

f.a // 1
f.b // 2
f.c // 3
```

### Generator与协程
Generator部署ajax:
```javascript
function* main() {
  var result = yield request("http://some.url");
  var resp = javascriptON.parse(result);
    console.log(resp.value);
}

function request(url) {
  makeAjaxCall(url, function(response){
    it.next(response);
  });
}

var it = main();
it.next();
```

## Generator函数的异步应用

### 回调
```javascript
fs.readFile('/etc/passwd', 'utf-8', function (err, data) {
  if (err) throw err;
  console.log(data);
});
```
问题出现在多个回调函数嵌套。假定读取A文件之后，再读取B文件，代码如下:
```javascript
fs.readFile(fileA, 'utf-8', function (err, data) {
  fs.readFile(fileB, 'utf-8', function (err, data) {
    // ...
  });
});
```
如果依次读取两个以上的文件，就会出现多重嵌套。代码不是纵向发展，而是横向发展，很快就会乱成一团，无法管理
只要有一个操作需要修改，它的上层回调函数和下层回调函数，可能都要跟着修改

### Promise
```javascript
var readFile = require('fs-readfile-promise');

readFile(fileA)
.then(function (data) {
  console.log(data.toString());
})
.then(function () {
  return readFile(fileB);
})
.then(function (data) {
  console.log(data.toString());
})
.catch(function (err) {
  console.log(err);
});
```
Promise 的写法只是回调函数的改进，使用then方法以后，异步任务的两段执行看得更清楚了，除此以外，并无新意
Promise 的最大问题是代码冗余，原来的任务被 Promise 包装了一下，不管什么操作，一眼看去都是一堆then，原来的语义变得很不清楚

### Generator函数
#### 协程
读文件的协程写法
```javascript
function *asyncJob() {
  // ...其他代码
  var f = yield readFile(fileA);
  // ...其他代码
}
```
#### Generator 函数的数据交换和错误处理
next返回值的value属性，是 Generator 函数向外输出数据；next方法还可以接受参数，向 Generator 函数体内输入数据
```javascript
function* gen(x){
  var y = yield x + 2;
  return y;
}

var g = gen(1);
g.next() // { value: 3, done: false }
g.next(2) // { value: 2, done: true }
```
Generator 函数内部还可以部署错误处理代码，捕获函数体外抛出的错误
```javascript
function* gen(x){
  try {
    var y = yield x + 2;
  } catch (e){
    console.log(e);
  }
  return y;
}

var g = gen(1);
g.next();
g.throw('出错了');
// 出错了
```

#### 异步任务的封装
```javascript
var fetch = require('node-fetch');

function* gen(){
  var url = 'https://api.github.com/users/github';
  var result = yield fetch(url);
  console.log(result.bio);
}
```
这样执行上面的代码：
```javascript
var g = gen();
var result = g.next();

result.value.then(function(data){
  return data.javascripton();
}).then(function(data){
  g.next(data);
});
```

### Thunk 函数
Thunk 函数是自动执行 Generator 函数的一种方法

#### Thunk函数的含义
编译器的“传名调用”实现，往往是将参数放到一个临时函数之中，再将这个临时函数传入函数体。这个临时函数就叫做 Thunk 函数
```javascript
function f(m) {
  return m * 2;
}

f(x + 5);

// 等同于

var thunk = function () {
  return x + 5;
};

function f(thunk) {
  return thunk() * 2;
}
```

#### JavaScript 语言的 Thunk 函数
在 JavaScript 语言中，Thunk 函数替换的不是表达式，而是**多参数函数**，
将其替换成一个**只接受回调函数作为参数的单参数函数**
```javascript
// 正常版本的readFile（多参数版本）
fs.readFile(fileName, callback);

// Thunk版本的readFile（单参数版本）
var Thunk = function (fileName) {
  return function (callback) {
    return fs.readFile(fileName, callback);
  };
};

var readFileThunk = Thunk(fileName);
readFileThunk(callback);
```
fs模块的readFile方法是一个多参数函数，两个参数分别为文件名和回调函数
经过转换器处理，它变成了一个单参数函数，只接受回调函数作为参数
这个单参数版本，就叫做 Thunk 函数

任何函数，只要参数有回调函数，就能写成 Thunk 函数的形式
```javascript
// ES5版本
var Thunk = function(fn){
  return function (){
    var args = Array.prototype.slice.call(arguments);
    return function (callback){
      args.push(callback);
      return fn.apply(this, args);
    }
  };
};

// ES6版本
var Thunk = function(fn) {
  return function (...args) {
    return function (callback) {
      return fn.call(this, ...args, callback);
    }
  };
};
```
用上面的转换器，生成fs.readFile的 Thunk 函数
```javascript
var readFileThunk = Thunk(fs.readFile);
readFileThunk(fileA)(callback);

// another example
function f(a, cb) {
  cb(a);
}
let ft = Thunk(f);

let log = console.log.bind(console);
ft(1)(log) // 1
```

#### Thunkify 模块
生产环境的转换器，建议使用 Thunkify 模块
```javascript
var thunkify = require('thunkify');
var fs = require('fs');

var read = thunkify(fs.readFile);
read('package.javascripton')(function(err, str){
  // ...
});
```

#### Generator 函数的流程管理
ES6 有了 Generator 函数，Thunk 函数现在可以用于 Generator 函数的自动流程管理
Generator函数可以自动执行
```javascript
var fs = require('fs');
var thunkify = require('thunkify');
var readFileThunk = thunkify(fs.readFile);

var gen = function* (){
  var r1 = yield readFileThunk('/etc/fstab');
  console.log(r1.toString());
  var r2 = yield readFileThunk('/etc/shells');
  console.log(r2.toString());
};
```

#### Thunk函数的自动流程管理
```javascript
function run(fn) {
  var gen = fn();

  function next(err, data) {
    var result = gen.next(data);
    if (result.done) return;
    result.value(next);
  }

  next();
}

function* g() {
  // ...
}

run(g);
```
```javascript
var g = function* (){
  var f1 = yield readFile('fileA');
  var f2 = yield readFile('fileB');
  // ...
  var fn = yield readFile('fileN');
};

run(g);
```
函数g封装了n个异步的读取文件操作，只要执行run函数，这些操作就会自动完成
这样一来，异步操作不仅可以写得像同步操作，而且一行代码就可以执行


## async函数
它就是 Generator 函数的语法糖
```javascript
var fs = require('fs');

var readFile = function (fileName) {
  return new Promise(function (resolve, reject) {
    fs.readFile(fileName, function(error, data) {
      if (error) reject(error);
      resolve(data);
    });
  });
};

var gen = function* () {
  var f1 = yield readFile('/etc/fstab');
  var f2 = yield readFile('/etc/shells');
  console.log(f1.toString());
  console.log(f2.toString());
};
```
写成async函数，如下：
```javascript
var asyncReadFile = async function () {
  var f1 = await readFile('/etc/fstab');
  var f2 = await readFile('/etc/shells');
  console.log(f1.toString());
  console.log(f2.toString());
};
```
async函数对 Generator 函数的改进，体现在以下四点:
+ 内置执行器
enerator 函数的执行必须靠执行器，所以才有了co模块，而async函数自带执行器。也就是说，async函数的执行，与普通函数一模一样，只要一行
```javascript
var result = asyncReadFile();
```
+ 更好的语义
async和await，比起星号和yield，语义更清楚了
async表示函数里有异步操作，await表示紧跟在后面的表达式需要等待结果

+ 更广的适用性
co模块约定，yield命令后面只能是 Thunk 函数或 Promise 对象
而async函数的await命令后面，可以是Promise 对象和原始类型的值（数值、字符串和布尔值，但这时等同于同步操作

+ 返回值是Promise
async函数的返回值是 Promise 对象，这比 Generator 函数的返回值是 Iterator 对象方便多了。你可以用then方法指定下一步的操作

进一步说，async函数完全可以看作多个异步操作，包装成的一个 Promise 对象，而await命令就是内部then命令的语法糖

### 用法
#### 基本用法
async函数返回一个 Promise 对象，可以使用then方法添加回调函数。当函数执行的时候，一旦遇到await就会先返回，等到异步操作完成，再接着执行函数体内后面的语句
```javascript
async function getStockPriceByName(name) {
  var symbol = await getStockSymbol(name);
  var stockPrice = await getStockPrice(symbol);
  return stockPrice;
}

getStockPriceByName('goog').then(function (result) {
  console.log(result);
});
```

### 语法
async函数的语法规则总体上比较简单，难点是错误处理机制
#### 返回Promise对象
async函数返回一个 Promise 对象
async函数内部return语句返回的值，会成为then方法回调函数的参数
```javascript
async function f() {
  return 'hello world';
}

f().then(v => console.log(v))
// "hello world"
```
函数f内部return命令返回的值，会被then方法回调函数接收到

async函数内部抛出错误，会导致返回的 Promise 对象变为reject状态。抛出的错误对象会被catch方法回调函数接收到
```javascript
async function f() {
  throw new Error('出错了');
}

f().then(
  v => console.log(v),
  e => console.log(e)
)
// Error: 出错了
```

#### Promise对象的状态变化
async函数返回的 Promise 对象，必须等到内部所有await命令后面的 Promise 对象执行完，才会发生状态改变，
除非遇到return语句或者抛出错误

#### await命令
正常情况下，await命令后面是一个 Promise 对象。如果不是，会被转成一个立即``resolve``的 Promise 对象
```javascript
async function f() {
  return await 123;
}

f().then(v => console.log(v))
// 123
```
await命令的参数是数值123，它被**转成 Promise 对象，并立即``resolve``**

await命令后面的 Promise 对象如果变为reject状态，则reject的参数会被catch方法的回调函数接收到
```javascript
async function f() {
  await Promise.reject('出错了');
}

f()
.then(v => console.log(v))
.catch(e => console.log(e))
// 出错了
```
只要一个await语句后面的 Promise 变为reject，那么**整个async函数都会中断执行**

如果将第一个await放在try...catch结构里面，这样不管这个异步操作是否成功，第二个await都会执行
```javascript
async function f() {
  try {
    await Promise.reject('出错了');
  } catch(e) {
  }
  return await Promise.resolve('hello world');
}

f()
.then(v => console.log(v))
// hello world
```

#### 错误处理
如果await后面的异步操作出错，那么**等同于async函数返回的 Promise 对象被reject**

防止出错的方法，也是将其放在try...catch代码块之中
如果有多个await命令，可以统一放在try...catch结构中

#### 使用注意点
1. await命令后面的Promise对象，运行结果可能是rejected，所以最好把await命令放在try...catch代码块中
2. 多个await命令后面的异步操作，如果不存在继发关系，最好让它们同时触发:
```javascript
// 写法一
let [foo, bar] = await Promise.all([getFoo(), getBar()]);

// 写法二
let fooPromise = getFoo();
let barPromise = getBar();
let foo = await fooPromise;
let bar = await barPromise;
```
如果确实希望多个请求并发执行，可以使用Promise.all方法
```javascript
async function dbFuc(db) {
  let docs = [{}, {}, {}];
  let promises = docs.map((doc) => db.post(doc));

  let results = await Promise.all(promises);
  console.log(results);
}

// 或者使用下面的写法

async function dbFuc(db) {
  let docs = [{}, {}, {}];
  let promises = docs.map((doc) => db.post(doc));

  let results = [];
  for (let promise of promises) {
    results.push(await promise);
  }
  console.log(results);
}
```
3. await命令只能用在async函数之中，如果用在普通函数，就会报错

#### 与其他异步处理方法的比较
通过一个例子，来看 async 函数与 Promise、Generator 函数的比较

>假定某个 DOM 元素上面，部署了一系列的动画，前一个动画结束，才能开始后一个。如果当中有一个动画出错，就不再往下执行，返回上一个成功执行的动画的返回值

Promise写法：
```javascript
function chainAnimationsPromise(elem, animations) {

  // 变量ret用来保存上一个动画的返回值
  var ret = null;

  // 新建一个空的Promise
  var p = Promise.resolve();

  // 使用then方法，添加所有动画
  for(var anim of animations) {
    p = p.then(function(val) {
      ret = val;
      return anim(elem);
    });
  }

  // 返回一个部署了错误捕捉机制的Promise
  return p.catch(function(e) {
    /* 忽略错误，继续执行 */
  }).then(function() {
    return ret;
  });

}
```
代码完全都是 Promise 的 API（then、catch等等），操作本身的语义反而不容易看出来

Generator写法：
```javascript
function chainAnimationsGenerator(elem, animations) {

  return spawn(function*() {
    var ret = null;
    try {
      for(var anim of animations) {
        ret = yield anim(elem);
      }
    } catch(e) {
      /* 忽略错误，继续执行 */
    }
    return ret;
  });

}
```
这个写法的问题在于，必须有一个任务运行器，自动执行 Generator 函数
上面代码的spawn函数就是自动执行器，它返回一个 Promise 对象
而且必须保证yield语句后面的表达式，必须返回一个 Promise

async写法：
```javascript
async function chainAnimationsAsync(elem, animations) {
  var ret = null;
  try {
    for(var anim of animations) {
      ret = await anim(elem);
    }
  } catch(e) {
    /* 忽略错误，继续执行 */
  }
  return ret;
}
```
Async函数的实现最简洁，最符合语义，几乎没有语义不相关的代码

#### 实例：按顺序完成异步操作
Promise写法：
```javascript
function logInOrder(urls) {
  // 远程读取所有URL
  const textPromises = urls.map(url => {
    return fetch(url).then(response => response.text());
  });

  // 按次序输出
  textPromises.reduce((chain, textPromise) => {
    return chain.then(() => textPromise)
      .then(text => console.log(text));
  }, Promise.resolve());
}
```
这种写法不太直观，可读性比较差

async写法：
```javascript
  for (const url of urls) {
    const response = await fetch(url);
    console.log(await response.text());
  }
}
```
这里的问题所有的fetch都是继发的，效率差，下面改写下使其并发请求：
```javascript
async function logInOrder(urls) {
  // 并发读取远程URL
  const textPromises = urls.map(async url => {
    const response = await fetch(url);
    return response.text();
  });

  // 按次序输出（因为按顺序遍历）
  for (const textPromise of textPromises) {
    console.log(await textPromise);
  }
}
```

#### 异步遍历器
TODO













